spring.application.name=eureka-server
server.port=8761

# Eureka ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false

# Actuator (requis pour le healthcheck Docker)
management.endpoints.web.exposure.include=health,info
